#!/usr/bin/env bash

source ../.env

ignore_files=(
  "help_text.json"
  "subscribe.json"
)

add_command() {
  endpoint="/applications/$APPLICATION_ID/commands"

  printf '%s\0' "${ignore_files[@]}" | grep -Fqz "$(basename $1)" && return;

  if [ ! -z "$GUILD" ]; then
    endpoint="/applications/$APPLICATION_ID/guilds/$GUILD/commands"
  fi

  curl -s \
    --url "https://discord.com/api/v8${endpoint}" \
    -X POST \
    -H "Authorization: Bot $DISCORD_TOKEN" \
    -H "Content-Type: application/json" \
    -d @"$1" \
    | (jq || cat) 2>/dev/null
}

for file in ./cmds/*.json; do
  add_command $file
done

# vim:ft=sh
