#!/usr/bin/env bash

ignore_files=(
  "help_text.json"
  "subscribe.json"
)

if [ -z "$GUILD" ]; then
  MODE="GLOBAL"
  endpoint="/applications/$APPLICATION_ID/commands"
else
  MODE="GUILD"
  endpoint="/applications/$APPLICATION_ID/guilds/$GUILD/commands"
fi

add_command() {
  printf '%s\0' "${ignore_files[@]}" | grep -Fqz "$(basename $1)" && return;

  [[ $(jq '.guildOnly?' "$1") == "true" && "$MODE" == "GLOBAL" ]] && return;

  curl -s \
    --url "https://discord.com/api/v8${endpoint}" \
    -X POST \
    -H "Authorization: Bot $DISCORD_TOKEN" \
    -H "Content-Type: application/json" \
    -d "$(jq 'del(.guildOnly)' "$1")" \
    | jq
}

for file in ./cmds/*.json; do
  add_command $file
done

# vim:ft=sh
